server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka



spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      globalcors:
#       corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://127.0.0.1:5501/"
#            allow-credentials: true   #추가
#            allowedHeaders:
#              - x-requested-with
#              - authorization
#              - content-type
#              - credential
#              - X-AUTH-TOKEN
#              - X-CSRF-TOKEN
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - OPTIONS
#              - DELETE
      routes:
        - id: first-service
          uri: http://localhost:8080/register
          predicates:
            - Path=/register/**
        - id: second-service
          uri: http://localhost:8080/login
          predicates:
          - Path=/login/**
        - id: third-service
          uri: http://localhost:8081/test
          predicates:
          - Path=/test/**
          filters:
          - UserJwtAuthorizationFilter
#        - id: sub-service
#          uri: http://localhost:8000/login
#          predicates:
#          - Path=/jwtsave/**
#          filters:
#          - JwtTokenSaveFilter         
#          filters:
#          - JwtAuthorizationFilter
          
#            
#          filters:
#          - AutorizationFilter
#        - id: second-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second-service/**

