server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezon=Asia/Seoul
    username: rlawldls11
    password: dlquf!2tkfkd!2
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 130822498758-70ukqnpe440h9k20oiio7707s2j6s8dt.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
  
